name = "front"
main = "src/worker.ts"
compatibility_date = "2026-04-23"
workers_dev = false

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[env.stage]
name = "front-stage"
workers_dev = true

[env.stage.observability]
enabled = true

[[env.stage.d1_databases]]
binding = "IDENTITY_DB"
database_name = "identity-stage"
database_id = "20dfc9c6-170c-47e7-927c-d703918a6449"

[env.stage.vars]
LOG_LEVEL = "info"
FRONTEND_ORIGIN = "https://front-stage.tachiiri.workers.dev"
GITHUB_OAUTH_CLIENT_ID = "Ov23lihhhvT7GB1IGasP"
GOOGLE_OAUTH_CLIENT_ID = "804252639051-hdkilk1189bomeiv9opnsu0h2basdtr8.apps.googleusercontent.com"
MICROSOFT_OAUTH_CLIENT_ID = "9350aec4-f659-4c8d-a48b-58c195844b09"
LAYOUTS_BUCKET_ID = "bucket-stage"
DEFAULT_ORG_ID = "9c95aa5e-5943-4dd0-9579-ed3725821979"
TURNSTILE_SITE_KEY = "0x4AAAAAAdmeMgvvrbA27oL6"

[[env.stage.services]]
binding = "BACKEND"
service = "backend-stage"

[env.production]
name = "front-production"
workers_dev = true

[env.production.observability]
enabled = true

[[env.production.d1_databases]]
binding = "IDENTITY_DB"
database_name = "identity-production"
database_id = "01fc4992-e113-435a-be70-226cddcfa092"

[env.production.vars]
LOG_LEVEL = "warn"
FRONTEND_ORIGIN = "https://front-production.tachiiri.workers.dev"
GITHUB_OAUTH_CLIENT_ID = "Ov23li098QXLtF5UbEg5"
GOOGLE_OAUTH_CLIENT_ID = "804252639051-hdkilk1189bomeiv9opnsu0h2basdtr8.apps.googleusercontent.com"
MICROSOFT_OAUTH_CLIENT_ID = "296697e1-f362-44d6-9895-df430f68c55c"
LAYOUTS_BUCKET_ID = "bucket-production"
DEFAULT_ORG_ID = "9c95aa5e-5943-4dd0-9579-ed3725821979"
TURNSTILE_SITE_KEY = "0x4AAAAAAdmeQIwvvS5sJHdN"

[[env.production.services]]
binding = "BACKEND"
service = "backend-production"

[env.dev]
name = "front-dev"
workers_dev = true

[env.dev.observability]
enabled = true

[[env.dev.d1_databases]]
binding = "IDENTITY_DB"
database_name = "identity-dev"
database_id = "38652751-ca79-47ae-ac3f-92b59088e11e"
remote = true

[[env.dev.services]]
binding = "BACKEND"
service = "backend-dev"

[env.dev.vars]
LOG_LEVEL = "debug"
FRONT_TO_BACKEND_TOKEN = "b109b22738647033f1ef4ad11426c8a8a05aae7c3ec3da9f88e0ad4dbd768781"
IDENTITY_ENCRYPTION_KEY = "bd4d0f574e5c354b3a0b1201ce20014ca38e98f934eaf7579dbdcba1ff96cf3b"
BUILD_SCREENS_TOKEN = "86c8bb6b73acd1df8017b08b1efdcec84a04da0e62f6591eee081ae91e8cd146"
GITHUB_OAUTH_CLIENT_ID = "Ov23litfbD8WRrXkM4iR"
GOOGLE_OAUTH_CLIENT_ID = "804252639051-hdkilk1189bomeiv9opnsu0h2basdtr8.apps.googleusercontent.com"
MICROSOFT_OAUTH_CLIENT_ID = "0398ec75-5040-4d01-8508-7aa813f2857c"
LAYOUTS_BUCKET_ID = "bucket-dev"
DEFAULT_ORG_ID = "9c95aa5e-5943-4dd0-9579-ed3725821979"
TURNSTILE_SITE_KEY = "0x4AAAAAAdmeIKiAf-H7Ql-x"

