import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const manifest = JSON.parse(
  readFileSync(resolve('dist/.vite/manifest.json'), 'utf-8'),
) as Record<string, { file: string }>;

const entry = manifest['src/web/client.ts'];
if (!entry) throw new Error('Client entry not found in vite manifest');

const path = `/${entry.file}`;
writeFileSync(
  resolve('src/client-path.ts'),
  `// Auto-generated by scripts/gen-client-path.ts — do not edit\nexport const CLIENT_JS_PATH = '${path}';\n`,
);
console.log(`CLIENT_JS_PATH → ${path}`);
