name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy to dev
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.10

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build && bun run gen-client-path

      - name: Build screens
        env:
          BASE_URL: https://front-dev.tachiiri.workers.dev
          BUILD_TOKEN: ${{ secrets.BUILD_SCREENS_TOKEN }}
        run: bun run build-screens

      - name: Set secrets (dev)
        run: echo "$SECRET" | bunx wrangler secret put TURNSTILE_SECRET_KEY --env dev
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOYMENT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          SECRET: ${{ secrets.TURNSTILE_SECRET_KEY_DEV }}

      - name: Deploy to dev
        run: bunx wrangler deploy --env dev
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOYMENT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
